# Generated by Django 4.0.2 on 2022-02-17 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_due_date_task_priority_task_start_date_and_more'),
        ('tasks', '0004_alter_subtask_task'),
    ]

    operations = [
    ]
